import {
  Accessibility,
  BellPlus,
  Inbox,
  Landmark,
  ScrollText,
  Tags,
  UsersRound,
  Bell,
  BookOpen,
  Bot,
  FileText,
  Flag,
  LayoutDashboard,
  LifeBuoy,
  Lock,
  MapPinned,
  ScanSearch,
  Scale,
  Settings,
  UserPlus,
  UserRound,
  type LucideIcon,
} from "lucide-react";
import type { ConsoleIcon } from "@/config/console";

/** Maps the icon keys held in `config/console` to concrete components. */
export const CONSOLE_ICONS: Record<ConsoleIcon, LucideIcon> = {
  scan: ScanSearch,
  assistant: Bot,
  flag: Flag,
  bell: Bell,
  map: MapPinned,
  recover: LifeBuoy,
  learn: BookOpen,
  documents: FileText,
  signIn: UserRound,
  register: UserPlus,
  dashboard: LayoutDashboard,
  settings: Settings,
  privacy: Lock,
  accessibility: Accessibility,
  terms: Scale,
  council: Landmark,
  queue: Inbox,
  users: UsersRound,
  categories: Tags,
  audit: ScrollText,
  alertDesk: BellPlus,
};
