/**
 * Shared vocabulary for scam analysis.
 *
 * Deliberately free of React and of any transport concern: the same shapes are
 * intended to describe a result whether it was produced in the browser for an
 * instant read or by the API once server-side checks exist. Requirements.md
 * modules 3 and 4 (FR13–FR24) are expressed here.
 */

/** FR14 — the channel the message arrived through. */
export type Channel = "sms" | "email" | "phone" | "website" | "social" | "other";

/** FR17 — the band a score falls into. */
export type RiskBand = "high" | "medium" | "low" | "unclear";

/** How strongly an indicator argues for a scam. */
export type IndicatorWeight = "high" | "medium" | "low";

/**
 * One reason contributing to a score.
 *
 * `evidence` is the fragment of the submission that triggered it — Rule 8.3
 * requires every result to carry the evidence it used, and showing the user the
 * exact words is what lets them disagree with the machine.
 */
export interface Indicator {
  id: string;
  label: string;
  detail: string;
  weight: IndicatorWeight;
  evidence?: string;
}

/** The broad kinds of attachment a submission can carry. */
export type MediaKind = "image" | "audio" | "video" | "document";

/**
 * What an image's own metadata says about how it was made.
 *
 * The distinction between a signed declaration and an unsigned hint is the
 * whole point of this type. A validated C2PA manifest saying "generated by
 * Firefly" is close to proof; the same claim sitting in an EXIF `Software` tag
 * is a string anybody can write with a hex editor. Collapsing the two into one
 * boolean would let the weaker of them borrow the authority of the stronger.
 *
 * `absent` is not evidence of anything. Every mainstream platform strips
 * metadata on upload, so the overwhelming majority of genuine scam screenshots
 * arrive with nothing at all — scoring that as suspicion would flag almost
 * every real submission the service receives.
 */
export type ProvenanceStatus =
  /** A validated manifest states a generative tool produced this. */
  | "declared-ai"
  /** A validated manifest states a camera or scanner captured this. */
  | "declared-capture"
  /** A manifest validated but says nothing either way about how it was made. */
  | "signed"
  /** A manifest is present and does not validate. Suspicious in itself. */
  | "untrusted"
  /** Unsigned metadata names a generator. A hint, not a declaration. */
  | "hinted-ai"
  /** Nothing to read. Means nothing. */
  | "absent";

export interface Provenance {
  status: ProvenanceStatus;
  /** The tool named as having produced the image, where one is named. */
  generator?: string;
  /** Signing authority. Present only where a manifest actually validated. */
  issuer?: string;
  /** Plain-language statement of what was found, shown to the reader as-is. */
  detail: string;
}

/**
 * What the on-device classifier made of an image.
 *
 * `probability` is the model's own number and is never promoted to a verdict on
 * its own. Detectors generalise poorly to generators they were not trained on,
 * so this is one indicator among several rather than the answer — which is why
 * it carries the checkpoint that produced it.
 */
/**
 * What a file says about itself, before anything judges it.
 *
 * Description rather than verdict: nothing here raises or lowers a score,
 * except the declared-versus-actual type mismatch, which the rule set reads
 * through `fileTypeMismatch`. It is shown whether or not anything was found,
 * because "we looked and it carries no camera record" is an answer and an
 * empty panel is not.
 */
export interface FileMetadata {
  name: string;
  sizeBytes: number;
  /** What the browser said the file was. */
  declaredType: string;
  /** What the file's own leading bytes say it is. */
  sniffedType?: string;
  sniffedLabel?: string;
  /** False only where the two disagree on the family, never on spelling. */
  typeMatches?: boolean;
  sha256?: string;
  lastModified?: number;

  /** Pixel dimensions as the container's own header declares them. */
  width?: number;
  height?: number;
  format?: string;
  bitDepth?: number;
  colour?: string;
  subsampling?: string;
  /** Estimated JPEG quality, or null where the table is not a scaled standard. */
  quality?: number | null;
  progressive?: boolean;
  interlaced?: boolean;
  iccProfile?: string | null;
  /** Metadata segments or chunks the container actually carries. */
  segments?: string[];

  exif?: {
    present: boolean;
    /** How many tags were found, so "present but sparse" is visible. */
    fields: number;
    make?: string;
    model?: string;
    lens?: string;
    software?: string;
    taken?: string;
    orientation?: number;
    capturedWidth?: number;
    capturedHeight?: number;
    gps?: { lat: number; lon: number } | null;
  };
}

/**
 * One structural or pixel-level reason to think an image was altered.
 *
 * Shaped like {@link Indicator} on purpose: an edit finding is evidence of the
 * same kind, and a reader should not have to learn a second vocabulary to read
 * the second half of the same report.
 */
export interface EditFinding {
  id: string;
  label: string;
  detail: string;
  weight: IndicatorWeight;
  evidence?: string;
}

/** Images only: what the on-device forensic pass could establish. */
export interface EditRead {
  findings: EditFinding[];
  /** Data URL of the error-level map, where the pixel pass could run. */
  heatmap?: string;
  /** What was actually inspected, so a quiet result can be read honestly. */
  examined?: string;
  /** Set in place of findings where the pass could not run at all. */
  unavailable?: string;
}

export interface SyntheticRead {
  /** 0–1 that the image was synthesised, as the model reports it. */
  probability: number;
  /** The checkpoint behind the number, so a verdict can be traced to it. */
  model: string;
  /** Set in place of a reading when the classifier could not run at all. */
  unavailable?: string;
}

/**
 * One uploaded file, reduced to what the rules can actually reason about.
 *
 * `extractedText` is filled where the contents could be read — today that means
 * text recognised in an image. Where it could not, `unreadable` says why, and
 * the analysis reports the gap rather than scoring around it: a screenshot that
 * failed to read is not the same as one that read clean.
 */
export interface MediaDescriptor {
  name: string;
  size: number;
  /** The browser's declared MIME type. May be empty. */
  type: string;
  kind: MediaKind;
  extractedText?: string;
  unreadable?: string;
  /** Images only: what the file's own metadata says about its origin. */
  provenance?: Provenance;
  /** Images only: what the on-device classifier made of the pixels. */
  synthetic?: SyntheticRead;
  /** Images only: whether the file shows signs of having been edited. */
  edits?: EditRead;
  /** Every file: what it says about itself, judged by nothing. */
  metadata?: FileMetadata;
}

/** FR13, FR14, FR19, FR22, FR23 — everything a submission can carry. */
export interface Submission {
  text: string;
  channel: Channel;
  media?: MediaDescriptor[];
}

/**
 * One thing the verdict was able — or unable — to look at.
 *
 * Reported alongside the score because a result is only as good as its inputs,
 * and a reader deciding how much weight to give a verdict is entitled to know
 * that the audio note in their submission was never listened to.
 */
export interface ExaminedSource {
  label: string;
  status: "read" | "not-read";
  detail: string;
}

/** FR16, FR17, FR18 — the analysis handed back to the user. */
export interface Analysis {
  /** 0–100. Higher means more scam-like. */
  score: number;
  band: RiskBand;
  /** 0–1. How much signal the submission actually gave us. */
  confidence: number;
  headline: string;
  summary: string;
  indicators: Indicator[];
  /** Anything extracted that is worth showing back: URLs, numbers, addresses. */
  extracted: {
    urls: string[];
    emails: string[];
    phones: string[];
  };
  /** What the verdict actually got to look at, source by source. */
  examined: ExaminedSource[];
}
