/**
 * Shared vocabulary for scam analysis.
 *
 * Deliberately free of React and of any transport concern: the same shapes are
 * intended to describe a result whether it was produced in the browser for an
 * instant read or by the API once server-side checks exist. Requirements.md
 * modules 3 and 4 (FR13–FR24) are expressed here.
 */

/** FR14 — the channel the message arrived through. */
export type Channel = "sms" | "email" | "phone" | "website" | "social" | "other";

/** FR17 — the band a score falls into. */
export type RiskBand = "high" | "medium" | "low" | "unclear";

/** How strongly an indicator argues for a scam. */
export type IndicatorWeight = "high" | "medium" | "low";

/**
 * One reason contributing to a score.
 *
 * `evidence` is the fragment of the submission that triggered it — Rule 8.3
 * requires every result to carry the evidence it used, and showing the user the
 * exact words is what lets them disagree with the machine.
 */
export interface Indicator {
  id: string;
  label: string;
  detail: string;
  weight: IndicatorWeight;
  evidence?: string;
}

/** The broad kinds of attachment a submission can carry. */
export type MediaKind = "image" | "audio" | "video" | "document";

/**
 * What an image's own metadata says about how it was made.
 *
 * The distinction between a signed declaration and an unsigned hint is the
 * whole point of this type. A validated C2PA manifest saying "generated by
 * Firefly" is close to proof; the same claim sitting in an EXIF `Software` tag
 * is a string anybody can write with a hex editor. Collapsing the two into one
 * boolean would let the weaker of them borrow the authority of the stronger.
 *
 * `absent` is not evidence of anything. Every mainstream platform strips
 * metadata on upload, so the overwhelming majority of genuine scam screenshots
 * arrive with nothing at all — scoring that as suspicion would flag almost
 * every real submission the service receives.
 */
export type ProvenanceStatus =
  /** A validated manifest states a generative tool produced this. */
  | "declared-ai"
  /** A validated manifest states a camera or scanner captured this. */
  | "declared-capture"
  /** A manifest validated but says nothing either way about how it was made. */
  | "signed"
  /** A manifest is present and does not validate. Suspicious in itself. */
  | "untrusted"
  /** Unsigned metadata names a generator. A hint, not a declaration. */
  | "hinted-ai"
  /** Nothing to read. Means nothing. */
  | "absent";

export interface Provenance {
  status: ProvenanceStatus;
  /** The tool named as having produced the image, where one is named. */
  generator?: string;
  /** Signing authority. Present only where a manifest actually validated. */
  issuer?: string;
  /** Plain-language statement of what was found, shown to the reader as-is. */
  detail: string;
}

/**
 * What the on-device classifier made of an image.
 *
 * `probability` is the model's own number and is never promoted to a verdict on
 * its own. Detectors generalise poorly to generators they were not trained on,
 * so this is one indicator among several rather than the answer — which is why
 * it carries the checkpoint that produced it.
 */
export interface SyntheticRead {
  /** 0–1 that the image was synthesised, as the model reports it. */
  probability: number;
  /** The checkpoint behind the number, so a verdict can be traced to it. */
  model: string;
  /** Set in place of a reading when the classifier could not run at all. */
  unavailable?: string;
}

/**
 * One uploaded file, reduced to what the rules can actually reason about.
 *
 * `extractedText` is filled where the contents could be read — today that means
 * text recognised in an image. Where it could not, `unreadable` says why, and
 * the analysis reports the gap rather than scoring around it: a screenshot that
 * failed to read is not the same as one that read clean.
 */
export interface MediaDescriptor {
  name: string;
  size: number;
  /** The browser's declared MIME type. May be empty. */
  type: string;
  kind: MediaKind;
  extractedText?: string;
  unreadable?: string;
  /** Images only: what the file's own metadata says about its origin. */
  provenance?: Provenance;
  /** Images only: what the on-device classifier made of the pixels. */
  synthetic?: SyntheticRead;
}

/** FR13, FR14, FR19, FR22, FR23 — everything a submission can carry. */
export interface Submission {
  text: string;
  channel: Channel;
  media?: MediaDescriptor[];
}

/**
 * One thing the verdict was able — or unable — to look at.
 *
 * Reported alongside the score because a result is only as good as its inputs,
 * and a reader deciding how much weight to give a verdict is entitled to know
 * that the audio note in their submission was never listened to.
 */
export interface ExaminedSource {
  label: string;
  status: "read" | "not-read";
  detail: string;
}

/** FR16, FR17, FR18 — the analysis handed back to the user. */
export interface Analysis {
  /** 0–100. Higher means more scam-like. */
  score: number;
  band: RiskBand;
  /** 0–1. How much signal the submission actually gave us. */
  confidence: number;
  headline: string;
  summary: string;
  indicators: Indicator[];
  /** Anything extracted that is worth showing back: URLs, numbers, addresses. */
  extracted: {
    urls: string[];
    emails: string[];
    phones: string[];
  };
  /** What the verdict actually got to look at, source by source. */
  examined: ExaminedSource[];
}
