import type { ContainerRead } from "@/lib/scam/containers";
import type { LinkReport } from "@/lib/scam/links";
import type { OriginAssessment } from "@/lib/scam/origin";
import type { HiddenRead } from "@/lib/scam/hidden";

/**
 * Shared vocabulary for scam analysis.
 *
 * Deliberately free of React and of any transport concern: the same shapes are
 * intended to describe a result whether it was produced in the browser for an
 * instant read or by the API once server-side checks exist. Requirements.md
 * modules 3 and 4 (FR13–FR24) are expressed here.
 */

/** FR14 — the channel the message arrived through. */
export type Channel = "sms" | "email" | "phone" | "website" | "social" | "other";

/** FR17 — the band a score falls into. */
export type RiskBand = "high" | "medium" | "low" | "unclear";

/** How strongly an indicator argues for a scam. */
export type IndicatorWeight = "high" | "medium" | "low";

/**
 * One reason contributing to a score.
 *
 * `evidence` is the fragment of the submission that triggered it — Rule 8.3
 * requires every result to carry the evidence it used, and showing the user the
 * exact words is what lets them disagree with the machine.
 */
export interface Indicator {
  id: string;
  label: string;
  detail: string;
  weight: IndicatorWeight;
  evidence?: string;
}

/** The broad kinds of attachment a submission can carry. */
export type MediaKind = "image" | "audio" | "video" | "document";

/**
 * What an image's own metadata says about how it was made.
 *
 * The distinction between a signed declaration and an unsigned hint is the
 * whole point of this type. A validated C2PA manifest saying "generated by
 * Firefly" is close to proof; the same claim sitting in an EXIF `Software` tag
 * is a string anybody can write with a hex editor. Collapsing the two into one
 * boolean would let the weaker of them borrow the authority of the stronger.
 *
 * `absent` is not evidence of anything. Every mainstream platform strips
 * metadata on upload, so the overwhelming majority of genuine scam screenshots
 * arrive with nothing at all — scoring that as suspicion would flag almost
 * every real submission the service receives.
 */
export type ProvenanceStatus =
  /** A validated manifest states a generative tool produced this. */
  | "declared-ai"
  /** A validated manifest states a camera or scanner captured this. */
  | "declared-capture"
  /** A manifest validated but says nothing either way about how it was made. */
  | "signed"
  /** A manifest is present and does not validate. Suspicious in itself. */
  | "untrusted"
  /** Unsigned metadata names a generator. A hint, not a declaration. */
  | "hinted-ai"
  /** Nothing to read. Means nothing. */
  | "absent";

export interface Provenance {
  status: ProvenanceStatus;
  /** The tool named as having produced the image, where one is named. */
  generator?: string;
  /** Signing authority. Present only where a manifest actually validated. */
  issuer?: string;
  /** Plain-language statement of what was found, shown to the reader as-is. */
  detail: string;
}

/**
 * What the on-device classifier made of an image.
 *
 * `probability` is the model's own number and is never promoted to a verdict on
 * its own. Detectors generalise poorly to generators they were not trained on,
 * so this is one indicator among several rather than the answer — which is why
 * it carries the checkpoint that produced it.
 */
/**
 * What a file says about itself, before anything judges it.
 *
 * Description rather than verdict: nothing here raises or lowers a score,
 * except the declared-versus-actual type mismatch, which the rule set reads
 * through `fileTypeMismatch`. It is shown whether or not anything was found,
 * because "we looked and it carries no camera record" is an answer and an
 * empty panel is not.
 */
export interface FileMetadata {
  name: string;
  sizeBytes: number;
  /** What the browser said the file was. */
  declaredType: string;
  /** What the file's own leading bytes say it is. */
  sniffedType?: string;
  sniffedLabel?: string;
  /** False only where the two disagree on the family, never on spelling. */
  typeMatches?: boolean;
  sha256?: string;
  lastModified?: number;

  /** Pixel dimensions as the container's own header declares them. */
  width?: number;
  height?: number;
  /**
   * The dimensions after the orientation flag is applied.
   *
   * Kept beside the stored frame rather than replacing it, because these are
   * the two numbers people compare. A phone writes a landscape frame plus
   * "rotate 90°"; every viewer and file inspector shows the portrait result.
   * Reporting only the stored frame is why this service's description of an
   * image did not match what its owner could see on their own machine.
   */
  displayWidth?: number;
  displayHeight?: number;
  format?: string;
  bitDepth?: number;
  colour?: string;
  hasAlpha?: boolean;
  subsampling?: string;
  /** Pixels per inch as the file declares it, not as it was resampled. */
  dpi?: number;
  /** Estimated JPEG quality, or null where the table is not a scaled standard. */
  quality?: number | null;
  progressive?: boolean;
  interlaced?: boolean;
  /** The profile's own name — "Display P3" — rather than merely "embedded". */
  iccProfile?: string | null;
  /** Metadata segments or chunks the container actually carries. */
  segments?: string[];
  /** EXIF orientation, and what it means in words. */
  orientation?: number;
  orientationLabel?: string;

  /** Whoever the file names as its author, from any of its metadata blocks. */
  author?: string;
  copyright?: string;
  /** The application that wrote the file, from EXIF, XMP or a container. */
  software?: string;
  description?: string;

  /** How many tags each metadata block carried. Zero is an answer. */
  tagCounts?: { exif: number; gps: number; xmp: number; iptc: number; icc: number };
  /**
   * Set where metadata is present but could not be parsed.
   *
   * The distinction this field exists to preserve: a file with no metadata and
   * a file whose metadata the reader failed on both used to come back as "no
   * metadata", and a reader could not tell which had happened.
   */
  metadataUnreadable?: string;

  exif?: {
    present: boolean;
    /** How many tags were found, so "present but sparse" is visible. */
    fields: number;
    make?: string;
    model?: string;
    lens?: string;
    /** Body or lens serial, where the camera wrote one. Identifies a device. */
    serial?: string;
    software?: string;
    /** When the shutter fired. */
    taken?: string;
    /** When it was digitised, which differs for a scan. */
    digitised?: string;
    /** When the file was last written, as the file itself records it. */
    changed?: string;
    /** The timezone offset the camera was set to, where it recorded one. */
    offset?: string;
    orientation?: number;
    capturedWidth?: number;
    capturedHeight?: number;
    /** Aperture, shutter, ISO and focal length, as one line. */
    exposure?: string;
    /** True where the file carries the camera's own embedded thumbnail. */
    thumbnail?: boolean;
    gps?: { lat: number; lon: number; altitude?: number } | null;
  };

  /** Non-images: what the PDF, archive or Office container states about itself. */
  container?: ContainerRead;
  /** Every file: what it carries that it has no reason to carry. */
  hidden?: HiddenRead;
}

/**
 * One structural or pixel-level reason to think an image was altered.
 *
 * Shaped like {@link Indicator} on purpose: an edit finding is evidence of the
 * same kind, and a reader should not have to learn a second vocabulary to read
 * the second half of the same report.
 */
export interface EditFinding {
  id: string;
  label: string;
  detail: string;
  weight: IndicatorWeight;
  evidence?: string;
}

/** Images only: what the on-device forensic pass could establish. */
export interface EditRead {
  findings: EditFinding[];
  /** Data URL of the error-level map, where the pixel pass could run. */
  heatmap?: string;
  /** What was actually inspected, so a quiet result can be read honestly. */
  examined?: string;
  /** Set in place of findings where the pass could not run at all. */
  unavailable?: string;
}

export interface SyntheticRead {
  /** 0–1 that the image was synthesised, as the model reports it. */
  probability: number;
  /** The checkpoint behind the number, so a verdict can be traced to it. */
  model: string;
  /** Set in place of a reading when the classifier could not run at all. */
  unavailable?: string;
}

/**
 * One uploaded file, reduced to what the rules can actually reason about.
 *
 * `extractedText` is filled where the contents could be read — today that means
 * text recognised in an image. Where it could not, `unreadable` says why, and
 * the analysis reports the gap rather than scoring around it: a screenshot that
 * failed to read is not the same as one that read clean.
 */
export interface MediaDescriptor {
  name: string;
  size: number;
  /** The browser's declared MIME type. May be empty. */
  type: string;
  kind: MediaKind;
  extractedText?: string;
  unreadable?: string;
  /** Images only: what the file's own metadata says about its origin. */
  provenance?: Provenance;
  /** Images only: what the on-device classifier made of the pixels. */
  synthetic?: SyntheticRead;
  /** Images only: whether the file shows signs of having been edited. */
  edits?: EditRead;
  /**
   * Images only: the single answer to "is this AI-generated?".
   *
   * Derived from the three readings above rather than stored alongside them,
   * so there is exactly one place in the codebase that decides what they add
   * up to and exactly one answer in the report.
   */
  origin?: OriginAssessment;
  /** Every file: what it says about itself, judged by nothing. */
  metadata?: FileMetadata;
}

/** FR13, FR14, FR19, FR22, FR23 — everything a submission can carry. */
export interface Submission {
  text: string;
  channel: Channel;
  media?: MediaDescriptor[];
  /**
   * Links, already inspected and where possible already followed.
   *
   * Passed in rather than produced by the analyser because following a link is
   * the one part of the check that needs the network, and the analyser is
   * deliberately pure. Where these are absent the analyser inspects each link's
   * address and says plainly that it did not follow it.
   */
  links?: LinkReport[];
}

/**
 * One thing the verdict was able — or unable — to look at.
 *
 * Reported alongside the score because a result is only as good as its inputs,
 * and a reader deciding how much weight to give a verdict is entitled to know
 * that the audio note in their submission was never listened to.
 */
export interface ExaminedSource {
  label: string;
  status: "read" | "not-read";
  detail: string;
}

/** FR16, FR17, FR18 — the analysis handed back to the user. */
export interface Analysis {
  /** 0–100. Higher means more scam-like. */
  score: number;
  band: RiskBand;
  /** 0–1. How much signal the submission actually gave us. */
  confidence: number;
  headline: string;
  summary: string;
  indicators: Indicator[];
  /** Anything extracted that is worth showing back: URLs, numbers, addresses. */
  extracted: {
    urls: string[];
    emails: string[];
    phones: string[];
  };
  /** One report per link: what it is, where it goes, and what is there. */
  links: LinkReport[];
  /** What the verdict actually got to look at, source by source. */
  examined: ExaminedSource[];
}
